version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: '21:00'
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    reviewers:
      - ttakuya50