#name: delete branch
#
## developに向けて出されたPRだけが対象
#on:
#  pull_request:
#    types: closed # プルリクをクローズしたタイミングだけで動かす
#    branches:
#      - 'develop'
#      - 'feature/**'
#
#jobs:
#  deleteBranch:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Delete branch
#        run: |
#          git push origin :${{ github.head_ref }}
