name: release

on:
  pull_request:
    types: closed # プルリクをクローズしたタイミングだけで動かす
    branches:
      - 'master'

# 参考:https://nvie:com/posts/a-successful-git-branching-model/#finishing-a-release-branch:
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install git-flow
        run: sudo apt-get install git-flow
      - name: Create tag name
        run: |
          if [ "`echo ${{ github.head_ref }} | grep release`" ]; then
            TAGNAME=$(echo ${{ github.head_ref }} | sed -e "s/release\///g")
          fi

          if [ "`echo ${{ github.head_ref }} | grep hotfix`" ]; then
            TAGNAME=$(echo ${{ github.head_ref }} | sed -e "s/hotfix\///g")
          fi

          echo "TAGNAME = $TAGNAME"
          echo "::set-env name=TAGNAME::$(echo $TAGNAME)"
      - name: Git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Finish release
        run: |
          git flow init
          git fetch origin
          git checkout develop
          git checkout master
          git flow init
          git flow release finish -m "${{ env.TAGNAME }}" -p ${{ env.TAGNAME }}
#      - name: Create tag
#        run: |
#          git fetch origin
#          git checkout origin/master
#          git tag "${{ env.TAGNAME }}"
#          git push origin "${{ env.TAGNAME }}"
#      - name: develop merge
#        run: |
#          git checkout ${{ github.head_ref }}
#          git checkout develop
#          git merge --no-ff ${{ github.head_ref }}
#          git push origin develop
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAGNAME }}
          release_name: Release ${{ env.TAGNAME }}
          draft: false
          prerelease: false
      - name: Delete branch
        run: |
          git push origin :${{ github.head_ref }}