name: release

on:
  pull_request:
    types: closed # プルリクをクローズしたタイミングだけで動かす
    branches:
      - 'release/**'
      - 'hotfix/**'

# 参考:https://nvie:com/posts/a-successful-git-branching-model/#finishing-a-release-branch:
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Create tag name
        run: |
          if [ "`echo ${{ github.head_ref }} | grep release`" ]; then
            TAGNAME=$(echo ${{ github.head_ref }} | sed -e "s/release\///g")
          fi

          if [ "`echo ${{ github.head_ref }} | grep hotfix`" ]; then
            TAGNAME=$(echo ${{ github.head_ref }} | sed -e "s/hotfix\///g")
          fi

          echo "TAGNAME = $TAGNAME"
          echo "::set-env name=TAGNAME::$(echo TAGNAME)"
#      - name: Create tag
#        run: |
#          git tag ${{ github.head_ref }}
#          git push origin --tags
      - name: master merge
        run: |
          git checkout master
          git merge --no-ff ${{ github.head_ref }}
          git tag -a ${{ env.TAGNAME }}
      - name: develop merge
        run: |
          git checkout develop
          git merge --no-ff ${{ github.head_ref }}
      - name: branch delete
        run: git branch -d ${{ github.head_ref }}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAGNAME }}
          release_name: Release ${{ env.TAGNAME }}
          draft: false
          prerelease: false

#      - name: Upload Release Asset
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
#          asset_path: ./${{ github.head_ref }}.zip
#          asset_name: ${{ github.head_ref }}.zip
#          asset_content_type: application/zip
